### ISSUE TITLE
Non-matching results in the DDR dataset

### ISSUE THREAD

**Issue by CristianoPatricio** [Sorades/CLAT#1]
Hi there,

Congratulations on this awesome work.
I'm trying to reproduce the results of Table II and III of the paper, specifically the results for the DDR dataset. After running over the 10-folds with the default parameters from the config files, the results I obtained deviate a little bit from the reported ones in the paper. I expected my results match the line "CLAT(Ours)" of both Tables for the DDR-subset column. Is there any other configuration for the DDR dataset?

Thanks in advance.

Cristiano

**Comment by Sorades** [comment]
Thank you for your interest in our work and for taking the time to reproduce our results!

There is no other specific configuration for the DDR dataset. I suspect that the deviations might be due to the training-time intervention, which is a trick borrowed from [CEM](https://github.com/mateoespinosa/cem)) that helps with test-time intervention.  We observed in our experiments that this strategy can occasionally affect model performance. You can try setting `training_int_prob` to 0 to disable it and see if that helps align your results with the reported ones.

**Comment by nguyenpbui** [comment]
Hi there, after setting `training_int_prob` to 0 but the results I obtained also deviate from the reported ones, especially the kappa and sensitivity. What do you think about this discrepancy?

Best regards.

**Comment by Sorades** [comment]
> Hi there, after setting `training_int_prob` to 0 but the results I obtained also deviate from the reported ones, especially the kappa and sensitivity. What do you think about this discrepancy?
> 
> Best regards.

Thanks for working on the reproduction! To help us troubleshoot, could you please confirm if the discrepancy was with the cait weight or the pretrained weight?

**Comment by nguyenpbui** [comment]
I think it's pretrained cait model. I use the following setting:

```
model:
  class_path: models.clat.CLAT
  init_args:
    arch_name: cait_xs24_384_concept
    pretrained: true
    disease_loss_weight: 1.0
    lesion_loss_weight: 0.6
    KG_loss_weight: 0.4
    with_EK: true
    training_int_prob: 0
    training_int_milestone: 10
```
